SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "A GraphQL schema and resolution system for C.")

SET(CPACK_PACKAGE_VENDOR "Workbench")
SET(CPACK_PACKAGE_CONTACT "Bruce Mitchener <bruce.mitchener@gmail.com>")

SET(CPACK_PACKAGE_VERSION_MAJOR "${GRAPHQL_VERSION_MAJOR}")
SET(CPACK_PACKAGE_VERSION_MINOR "${GRAPHQL_VERSION_MINOR}")
SET(CPACK_PACKAGE_VERSION_PATCH "${GRAPHQL_VERSION_PATCH}")

SET(CPACK_PACKAGE_FILE_NAME "${CMAKE_PROJECT_NAME}_${GRAPHQL_VERSION}-${GRAPHQL_TARGET_PLATFORM}")
SET(CPACK_SOURCE_PACKAGE_FILE_NAME "${CMAKE_PROJECT_NAME}_${GRAPHQL_VERSION}-sources")

SET(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/LICENSE.rst")
SET(CPACK_RESOURCE_FILE_README "${CMAKE_SOURCE_DIR}/README.rst")

SET(CPACK_SOURCE_IGNORE_FILES
    "/build.*"
    "/.git"
)

SET(CPACK_DEBIAN_PACKAGE_HOMEPAGE "https://github.com/waywardmonkeys/graphql/")
SET(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
SET(CPACK_DEBIAN_PACKAGE_SECTION "libraries")

INCLUDE(CPack)
